services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: js_app
    ports:
      - 8000:8000
    volumes:
      - .:/app
      - /app/node_modules 
    command: ["node", "main.js"]